[package]
name        = "cl_engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "cl_engine"

[[bin]]
name = "cl_engine"
path = "src/main.rs"

[dependencies]
cl_core     = { workspace = true }
cl_input    = { workspace = true }
cl_scene    = { workspace = true }
cl_render   = { workspace = true }
cl_servers  = { workspace = true }
cl_platform = { workspace = true }

winit      = { workspace = true }
wgpu       = { workspace = true }
log        = { workspace = true }
env_logger = { workspace = true }
pollster   = { workspace = true }
