[package]
name        = "gd_engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "gd_engine"

[[bin]]
name = "gd_engine"
path = "src/main.rs"

[dependencies]
gd_core   = { workspace = true }
gd_input  = { workspace = true }
gd_scene  = { workspace = true }
gd_render = { workspace = true }

winit    = { workspace = true }
wgpu     = { workspace = true }
log      = { workspace = true }
env_logger = { workspace = true }
pollster = { workspace = true }
